version: '3.8'
services:
  db:
    build: ./pg
    restart: always
    volumes:
      - /opt/odclive/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - web
  api:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      YT_CHANNEL: ${YT_CHANNEL}
      GOOGLE_KEY: ${GOOGLE_KEY} 
      API_WEBSITE: ${API_WEBSITE}
      SND_ID: ${SND_ID}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - /opt/odclive/uploads:/usr/src/app/uploads
      - ./submodules:/usr/src/app/submodules/
      - ${FONTS_DIR}:/root/.fonts
    labels:
      - traefik.http.routers.api.rule=Host(`api.zest.radio`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.services.api.loadbalancer.server.port=4000
    networks:
      - web
  chat:
    build: ./submodules/chat
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    labels:
      - traefik.http.routers.chat.rule=Host(`chat.zest.radio`)
      - traefik.http.routers.chat.tls=true
      - traefik.http.routers.chat.tls.certresolver=le
      - traefik.http.services.chat.loadbalancer.server.port=8080
    networks:
      - web
  admin:
    build: ./submodules/admin
    restart: always
    labels:
      - traefik.http.routers.admin.rule=Host(`admin.zest.radio`)
      - traefik.http.routers.admin.tls=true
      - traefik.http.routers.admin.tls.certresolver=le
      - traefik.http.services.admin.loadbalancer.server.port=3000
    networks:
      - web
  cli:
    build: ./submodules/cli
    restart: always
    networks:
      - web
  ssr_proxy:
    build: ./submodules/ssr_proxy
    restart: always
    environment:
      TARGET_SRV: ${TARGET_SRV}
    labels:
      - traefik.http.routers.web.rule=Host(`zest.radio`, `www.zest.radio`)
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=le
      - traefik.http.middlewares.redir.redirectregex.regex=^https://www.zest.radio/(.*)
      - traefik.http.middlewares.redir.redirectregex.replacement=https://zest.radio/$${1}
      - traefik.http.middlewares.redir.redirectregex.permanent=true
      - traefik.http.routers.web.middlewares=redir
    networks:
      - web
networks:
  web:
    external: true
