version: '3.1'
services:
  db:
    build: ./pg
    restart: always
    environment:
      POSTGRES_DB: odclive
      POSTGRES_PASSWORD: develop
  api:
    build: ./pm2
    environment:
      DB_HOST: db
      DB_NAME: odclive
      DB_USER: postgres
      DB_PASSWORD: develop
      DB_PORT: 5432
      JWT_SECRET: develop
      YT_CHANNEL: YOURCHANNELID
      GOOGLE_KEY: YOURGOOGLEAPIKEY
    volumes:
      - .:/app
    ports:
      - 8081:4000
  web:
    build: ./vuedev
    volumes:
      - ./cli:/app
    ports:
      - 8082:8080
  app:
    build: ./vuedev
    volumes:
      - ./app:/app
    ports:
      - 8083:8080
  chat:
    build: ./pm2
    environment:
      DB_HOST: db
      DB_NAME: odclive
      DB_USER: postgres
      DB_PASSWORD: develop
      DB_PORT: 5432
    volumes:
      - ./chat:/app
    ports:
      - 8080:80
