version: '3.8'
services:
  db:
    build: ./pg
    restart: always
    volumes:
      - /opt/odclive/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  api:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      YT_CHANNEL: ${YT_CHANNEL}
      GOOGLE_KEY: ${GOOGLE_KEY} 
      API_WEBSITE: ${API_WEBSITE}
      SND_ID: ${SND_ID}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - /opt/odclive/uploads:/usr/src/app/uploads
      - ./submodules:/usr/src/app/submodules/
      - ${FONTS_DIR}:/root/.fonts
    ports:
      - 8081:4000
  chat:
    build: ./submodules/chat
    environment:
      DB_HOST: db
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - 8080:8080
  admin:
    build: ./submodules/admin
    ports:
      - 8082:5000
  cli:
    build: ./submodules/cli
    ports:
      - 8083:8080
  ssr_proxy:
    build: ./submodules/ssr_proxy
    ports:
      - 8085:8080
    environment:
      TARGET_SRV: cli
