version: '3.1'
services:
  db:
    build: ./pg
    restart: always
    environment:
      POSTGRES_PASSWORD: develop
    ports:
      - 5432:5432
  api:
    build: ./pm2
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: develop
      DB_PORT: 5432
      JWT_SECRET: develop
    volumes:
      - .:/app
    ports:
      - 8081:4000
