version: '3.1'
services:
  db:
    build: ./pg
    restart: always
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: odclive
      POSTGRES_PASSWORD: develop
  api:
    build: ./pm2
    environment:
      DB_HOST: db
      DB_NAME: odclive
      DB_USER: postgres
      DB_PASSWORD: develop
      DB_PORT: 5432
      JWT_SECRET: develop
      YT_CHANNEL: YOURCHANNELID
      GOOGLE_KEY: YOURGOOGLEAPIKEY
      API_WEBSITE: http://localhost:8081
    volumes:
      - .:/app
    ports:
      - 8081:4000
  chat:
    build: ./chat
    environment:
      DB_HOST: db
      DB_NAME: odclive
      DB_USER: postgres
      DB_PASSWORD: develop
      DB_PORT: 5432
    ports:
      - 8080:8080
  admin:
    build: ./vuedev
    volumes:
      - ./admin:/app
    ports:
      - 8082:8080
  cli:
    build: ./cli
    ports:
      - 8083:5000
  app:
    build: ./app
    ports:
      - 8084:5000
